"""A 3D CNC G-Code visualizer."""
# pylint: disable=invalid-name, global-statement, too-many-locals, too-many-branches, too-many-statements, too-many-arguments, too-many-positional-arguments

import argparse
import math
import os
import re
import sys

import dearpygui.dearpygui as dpg  # pylint: disable=import-error

# Global tracking variables
current_pos = [0.0, 0.0, 0.0]  # X, Y, Z
# Stores tuples: (start_pt, end_pt, is_rapid, line_idx)
toolpaths = []
gcode_lines = []
current_line = 0  # Tracks how many G-Code lines to draw


def parse_gcode(file_path):
    """Parse a G-Code file and extract toolpaths."""
    toolpaths.clear()
    gcode_lines.clear()

    with open(file_path, 'r', encoding="utf-8") as f:
        current_g = "G0"

        for line in f:
            raw_line = line.strip()
            line = raw_line.upper()
            line = line.split(';')[0].split('(')[0].strip()

            if not line:
                continue

            line_idx = len(gcode_lines)
            gcode_lines.append(f"{line_idx + 1}: {raw_line}")

            if "G0" in line:
                current_g = "G0"
            if "G1" in line:
                current_g = "G1"
            if "G2" in line:
                current_g = "G2"
            if "G3" in line:
                current_g = "G3"

            x_match = re.search(r'X\s*([-+]?\d*\.\d+|\d+)', line)
            y_match = re.search(r'Y\s*([-+]?\d*\.\d+|\d+)', line)
            z_match = re.search(r'Z\s*([-+]?\d*\.\d+|\d+)', line)
            i_match = re.search(r'I\s*([-+]?\d*\.\d+|\d+)', line)
            j_match = re.search(r'J\s*([-+]?\d*\.\d+|\d+)', line)

            if not (x_match or y_match or z_match):
                continue

            start_pt = list(current_pos)
            if x_match:
                current_pos[0] = float(x_match.group(1))
            if y_match:
                current_pos[1] = float(y_match.group(1))
            if z_match:
                current_pos[2] = float(z_match.group(1))
            end_pt = list(current_pos)

            is_rapid = current_g == "G0"

            if current_g in ("G2", "G3"):
                i_val = float(i_match.group(1)) if i_match else 0.0
                j_val = float(j_match.group(1)) if j_match else 0.0

                cx = start_pt[0] + i_val
                cy = start_pt[1] + j_val
                r = math.sqrt(i_val**2 + j_val**2)

                if r > 0.0001:
                    angle_start = math.atan2(start_pt[1] - cy, start_pt[0] - cx)
                    angle_end = math.atan2(end_pt[1] - cy, end_pt[0] - cx)

                    if current_g == "G3":  # Counter-clockwise
                        if angle_end <= angle_start:
                            angle_end += 2 * math.pi
                    else:  # Clockwise
                        if angle_end >= angle_start:
                            angle_end -= 2 * math.pi

                    arc_angle = abs(angle_end - angle_start)
                    segments = max(1, int(math.degrees(arc_angle) / 5.0))

                    prev_pt = list(start_pt)
                    for step in range(1, segments + 1):
                        t = step / segments
                        cur_angle = angle_start + (angle_end - angle_start) * t

                        step_x = cx + r * math.cos(cur_angle)
                        step_y = cy + r * math.sin(cur_angle)
                        step_z = start_pt[2] + (end_pt[2] - start_pt[2]) * t

                        next_pt = [step_x, step_y, step_z]
                        # Attach line_idx to every sub-segment generated by the arc
                        toolpaths.append((prev_pt, next_pt, False, line_idx))
                        prev_pt = next_pt
                else:
                    toolpaths.append((start_pt, end_pt, False, line_idx))
            else:
                toolpaths.append((start_pt, end_pt, is_rapid, line_idx))


def project_iso(x, y, z, scale=4.0, offset_x=300, offset_y=600):
    """Converts 3D CNC coordinates into 2D screen pixels"""
    angle = math.radians(30)
    screen_x = (x - y) * math.cos(angle) * scale + offset_x
    screen_y = offset_y - (x + y) * math.sin(angle) * scale - (z * scale)
    return [screen_x, screen_y]


# --- UI Callbacks and Drawing Logic ---


def update_canvas():
    """Clears the drawlist and redraws paths up to current_line"""
    # Clear existing lines from the drawlist
    dpg.delete_item("drawlist", children_only=True)

    # Find how many toolpaths to draw based on current_line
    max_idx = 0
    for tp in toolpaths:
        if tp[3] < current_line:
            max_idx += 1
        else:
            break

    # Update the tracking text based on the current line
    if current_line > 0 and current_line <= len(gcode_lines):
        current_gcode_text = gcode_lines[current_line - 1]
        dpg.set_value("gcode_line_text", f"Current Line: {current_gcode_text}")
        dpg.set_value("gcode_listbox", current_gcode_text)
    else:
        dpg.set_value("gcode_line_text", "Current Line: (Empty)")
        if gcode_lines:
            dpg.set_value("gcode_listbox", gcode_lines[0])

    for i in range(max_idx):
        start, end, is_rapid, _ = toolpaths[i]
        p1 = project_iso(start[0], start[1], start[2])
        p2 = project_iso(end[0], end[1], end[2])

        if is_rapid:
            dpg.draw_line(p1,
                          p2,
                          color=[255, 140, 0, 200],
                          thickness=1,
                          parent="drawlist")
        else:
            dpg.draw_line(p1,
                          p2,
                          color=[0, 255, 255, 255],
                          thickness=2,
                          parent="drawlist")


def next_step():
    """Advance to the next G-Code line."""
    global current_line
    if current_line < len(gcode_lines):
        current_line += 1
        dpg.set_value("step_slider", current_line)
        update_canvas()


def prev_step():
    """Go back to the previous G-Code line."""
    global current_line
    if current_line > 0:
        current_line -= 1
        dpg.set_value("step_slider", current_line)
        update_canvas()


def slider_changed(_sender, app_data):
    """Update current line from slider."""
    global current_line
    current_line = app_data
    update_canvas()


def on_resize(_sender, _app_data):
    """Dynamically scales the drawlist to fit the viewport."""
    vp_width = dpg.get_viewport_client_width()
    vp_height = dpg.get_viewport_client_height()

    if dpg.does_item_exist("drawlist"):
        # Subtract ~80px for the top controls and padding
        new_height = max(100, vp_height - 80)
        # Subtract ~320px to leave room for the right-side listbox
        new_width = max(100, vp_width - 320)

        dpg.set_item_width("drawlist", new_width)
        dpg.set_item_height("drawlist", new_height)
        
    if dpg.does_item_exist("gcode_listbox"):
        # DearPyGui listboxes require an explicit 'num_items' to fill vertical space.
        # Estimate row height (~18px) and calculate the amount of items that fit vertically.
        num_items = max(3, (vp_height - 40) // 18)
        dpg.configure_item("gcode_listbox", num_items=num_items)


def main():
    """Main entry point for the application."""
    global current_line

    # --- Command Line Arguments ---
    parser = argparse.ArgumentParser(description="Visualize CNC G-Code in 3D.")
    parser.add_argument("filepath",
                        help="Path to the .nc G-Code file to visualize")
    args = parser.parse_args()

    if not os.path.exists(args.filepath):
        print(f"Error: The file '{args.filepath}' could not be found.")
        sys.exit(1)

    # Parse the file provided via command line
    parse_gcode(args.filepath)

    # Set the initial line to 0 (empty canvas)
    current_line = 0

    # Initialize DearPyGui
    dpg.create_context()
    dpg.create_viewport(title="cam", width=1024, height=768)

    # Bind the dynamic resize function
    dpg.set_viewport_resize_callback(on_resize)

    # --- UI Setup ---
    with dpg.window(tag="primary_window"):  # type: ignore
        with dpg.group(horizontal=True):  # type: ignore

            # 1. Left Panel (Controls + Canvas)
            # width=-300 means "take up all space EXCEPT 300 pixels"
            # height=-1 forces it to use full vertical window height
            with dpg.child_window(width=-300, height=-1, border=False):  # type: ignore

                # Control Panel
                with dpg.group(horizontal=True):  # type: ignore
                    dpg.add_button(label="< Prev", callback=prev_step)
                    dpg.add_button(label="Next >", callback=next_step)
                    dpg.add_slider_int(label="Line",
                                       tag="step_slider",
                                       min_value=0,
                                       max_value=len(gcode_lines),
                                       default_value=current_line,
                                       callback=slider_changed,
                                       width=250)

                    dpg.add_text("Current Line: (Empty)", tag="gcode_line_text")

                dpg.add_separator()

                # Canvas
                with dpg.drawlist(tag="drawlist", width=700,
                                  height=650):  # type: ignore
                    pass

            # 2. Right Panel (G-Code List)
            # added height=-1 here to stretch the container to the floor of the viewport
            with dpg.child_window(width=280, height=-1, border=False):  # type: ignore
                # Dynamically updated in on_resize to fill the entire vertical height
                dpg.add_listbox(items=gcode_lines,
                                tag="gcode_listbox",
                                width=-1,
                                num_items=35)

    # Run the initial draw to set the starting state
    update_canvas()

    # Finish Viewport Configuration
    dpg.setup_dearpygui()
    dpg.show_viewport()

    # Lock the main window to the viewport limits
    dpg.set_primary_window("primary_window", True)

    dpg.start_dearpygui()
    dpg.destroy_context()


if __name__ == "__main__":
    main()
